dataset_name: churn_lastfm_days
batch_size: 128
learning_rate: .01
log_interval: 1000
weight_decay: 1.e-2
num_epochs: 1000
axis: 2
landmark: True
target_lr: .01
arch:
  type: transformer
  arch_kwargs:
    hidden_size: 16
    seq_len: 100  # Has to be the same as the horizon
    output_dim: 8
    num_layers: 1
    dropout: 0.05

output_file: Results/{}/

preprocessed_data: False
calculate_tgt_and_mask: True
dataset_kwargs:
  horizon: 100
  data_path: ../data/lastfm-dataset-1K

lambda_: 0.9
num_steps: 5
verbose: True