dataset_name: pbc2
axis: 2  # For lambda baseline this has to be 1.
batch_size: 128
learning_rate: .1
log_interval: 1000
weight_decay: 0.0
num_epochs: 100
output_file: Results/{}/
landmark: True
target_lr: .5
arch:
  type: linear
  arch_kwargs:
    hidden_size: 16
    seq_len: 100  # Has to be the same as the horizon
    output_dim: 8
    num_layers: 1
    dropout: 0.05

preprocessed_data: False
dataset_kwargs:
  horizon: 16
  data_path: data/PBC.pkl

lambda_: 0.0
num_steps: 5
verbose: False